apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: text-lines-topic
  namespace: confluent
spec:
  kafkaRestClassRef:
    name: krc-cfk
  replicas: 3
  partitionCount: 4
  configs:
    cleanup.policy: "delete"